[package]
name = "dirsum"
version = "0.1.0"
authors = ["everettjf <everettjf@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filesize = "0.2.0"